language: node_js
node_js:
- stable
install:
- npm install
- ng run build-prod
script:
- npm test
after_success:
- npm run coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
